# English path redirects
# Force because the files exist (root paths still resolve to English)
[[redirects]]
  from = "/"
  to = "/en/"
  force = true
[[redirects]]
  from = "/team"
  to = "/en/team"
  force = true
[[redirects]]
  from = "/goals"
  to = "/en/goals"
  force = true
[[redirects]]
  from = "/goals"
  to = "/en/goals"
  force = true
[[redirects]]
  from = "/newsroom"
  to = "/en/newsroom"
  force = true
[[redirects]]
  from = "/media"
  to = "/en/media"
  force = true
